### ISSUE TITLE
OpenCV Image Recognition and Gestures 

### ISSUE THREAD

**Issue by dambem** [dambem/ClimateMonitorV2#18]
## Description
Using the OpenCV Library, we can implement some seriously cool stuff.
https://docs.opencv.org/3.4/d4/d76/tutorial_js_morphological_ops.html
https://www.npmjs.com/package/opencv4nodejs

Essentially, we're wanting to display the "Invisible Pollution" through the use of a fogging effect based on pollution levels. Whether this would be through the use of a fog png overlaid on top of a pre-existing image is up for discussion (which is why this issue has been set up) but there's some amazing stuff that can be done.

Additionally, it can also do hand recognition. This will let us showcase something like we wanted to with the use of the leap motion but without need for people to actually have the equipment

https://medium.com/@muehler.v/simple-hand-gesture-recognition-using-opencv-and-javascript-eb3d6ced28a0

All in all, a lot of cool stuff, so want to open this issue up for discussion for any other features. @AlvaroRausell  is putting the work in popping it into the opencv branch.

**Comment by AlvaroRausell** [comment]
In order to get `OpenCV` working on Linux:

1. Download the source from [the official site](https://github.com/opencv/opencv/archive/4.3.0.zip)
2. Extract the archive
3. Within the output of the previous step, create a directory with an arbitrary name (`build` for instance)
4. Run:
```
cd <dir from step 3> && cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..

make
sudo make install
```
5. Install `opencv` via `npm`

**Comment by dambem** [comment]
Most likely not using this so closing for now
