### ISSUE TITLE
Prevent people directly commiting to master 

### ISSUE THREAD

**Issue by Heverett94** [dambem/ClimateMonitorV2#38]
## Description
Need something to block people commiting to master before review, to avoid breaking stuff

## Additional Information
Because I'm dumb and just did this despite making a branch

**Comment by Heverett94** [comment]
I believe this can only be done by someone who is an administrator on this repo

**Comment by M-Davies** [comment]
What usually needs to be done is you need to add branch protection ruling to the master branch. This allows you to specify a bunch of different restrictions on the branch including PR's only, reviews are required, etc. And yeah, this can only be done by someone with admin access (@dambem wink nudge) 
<img width="1097" alt="Screenshot 2020-06-21 at 13 03 15" src="https://user-images.githubusercontent.com/25231953/85224094-abc28980-b3bf-11ea-9566-3dd78c46a82f.png">

**Comment by dambem** [comment]
I'll add that change cheers!

**Comment by dambem** [comment]
Okay, so just changed it, should now require a review with one reviewer minimum so will stop people (especially me as it's a habit) from pushing directly into master
