### ISSUE TITLE
Add animations

### ISSUE THREAD

**Issue by M-Davies** [dambem/ClimateMonitorV2#46]
## Description
Not sure if this is feasible in a standard node app but it's worth investigating if nothing else. It would be nice if we added some animations to certain events on the page. Some ideas:
- ~`What is PM10 and PM2.5?` could have a nice transition animation when moving from collapsed to open~ After investigation, there aren't any transformation options that I could find that are better than one we currently have
- The page in general could "generate" when it's loaded (hard to explain, if I find an example I'll add it to the comments)
- `Health Effects` section could be touched up a little bit, using gifs of sick vs healthy people instead of just red and black figures

**Comment by dambem** [comment]
Definitely think it's worth some work. There's a lot of inbuilt animation stuff in jquery that would definitely add a lot to the design

https://www.w3schools.com/jquery/jquery_animate.asp
