### ISSUE TITLE
Split up Current Average Pollution Levels section

### ISSUE THREAD

**Issue by M-Davies** [dambem/ClimateMonitorV2#48]
## Description
<img width="996" alt="Screenshot 2020-06-21 at 13 38 02" src="https://user-images.githubusercontent.com/25231953/85224757-72404d00-b3c4-11ea-832d-534df51888b2.png">
This is a little constrained, tight and hard to read. I'd like to split this up a little bit to make it prettier

**Comment by dambem** [comment]
Definitely a good shout!
