### ISSUE TITLE
Design Improvements

### ISSUE THREAD

**Issue by dambem** [dambem/ClimateMonitorV2#5]
In it's current state, the website design is quite ugly, and could use some beautifying

**Comment by M-Davies** [comment]
Started up a figma to start drawing up some rough designs https://www.figma.com/file/je93UCnKuQWpWxdx24FQQ6/Sheffsense?node-id=0%3A1

**Comment by M-Davies** [comment]
I'm going to start creating sub issues of this for a few ideas I have to make the home page look a bit prettier. These will all be under the [DESIGN IMPROVEMENTS](https://github.com/dambem/ClimateMonitorV2/labels/Design%20Improvements) label

**Comment by dambem** [comment]
Quite happy with these improvements!
