### ISSUE TITLE
Sideways Menu

### ISSUE THREAD

**Issue by dambem** [dambem/ClimateMonitorV2#57]
## Description
This is more of a dashboard. A side menu would be quite a lot better looking for users, and i think just make everything look a little bit nicer. 

## Steps to reproduce
n/a 

## The actual vs expected behaviour
actual behaviour - it's at the top 
expected - we want it to be at the side

**Comment by M-Davies** [comment]
~Any preference on the side? left or right?~ For the record, left was the choice
