### ISSUE TITLE
Pre-Existing Python Graphs on Website

### ISSUE THREAD

**Issue by dambem** [dambem/ClimateMonitorV2#64]
## Description
in public/files we have a couple of nice looking long term python visualisations! Could be good to get them displayed somewhere on the page.

**Comment by M-Davies** [comment]
@dambem @Megan-Wright How good are your webdev skills? I'm having some trouble getting a [slick carosel](https://kenwheeler.github.io/slick/) working without much success. I've been following [a tutorial](https://www.youtube.com/watch?v=hyr2zasS27w) but I can't get anything displaying. Even when going down to the absolute bare bones of what slick needs to run, I just get a white void where slick should be. Could you take a look at my branch and see if there's anything obious I'm doing wrong?

https://github.com/dambem/ClimateMonitorV2/tree/caroseled_python_graphs

**Comment by dambem** [comment]
Is there any proper reason as to why you're not just using the bootstrap carousels? As they might be a little easier to sort out https://getbootstrap.com/docs/4.0/components/carousel/

**Comment by dambem** [comment]
Took a bit of a look at your changes, it might be due to 
`    script(type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js")
`
being in the first 4 lines but not in the footer. A lot of these javascript imports require being put in the footer after the initial page is loading (for god knows why!!)

**Comment by M-Davies** [comment]
> Is there any proper reason as to why you're not just using the bootstrap carousels? As they might be a little easier to sort out https://getbootstrap.com/docs/4.0/components/carousel/

Mostly because I found it hard to get my head around yesterday. Slick seemed a lot easier to work out.

EDIT: I got the bootstrap one working now so I'll use that one instead
