### ISSUE TITLE
Grey mapbox

### ISSUE THREAD

**Issue by M-Davies** [dambem/ClimateMonitorV2#67]
## Description
- I have a grey mapbox whenever I start the application (see image). Refreshing the page, uninstalling packages and reinstalling and restarting my computer have not worked.
- I have also tried dropping my node version from `13.2.0` to `12.14.1` and I still see this problem.
- I'm using Chrome version `83.0.4103.106` and can confirm I see this error in Firefox too. 
<img width="1568" alt="Screenshot 2020-06-25 at 10 31 37" src="https://user-images.githubusercontent.com/25231953/85694597-2c8ac980-b6cf-11ea-956d-3d36bf599edc.png">

## Steps to reproduce
1. Clone Repo
2. npm i
3. npm start

## The actual vs expected behaviour
Map appears grey vs map appears normally

**Comment by dambem** [comment]
Think this is fixed now, but i'm gonna open a related issue about using secrets properly as the config.js isn't the best solution for what we're doing
