### ISSUE TITLE
Start using git secrets properly 

### ISSUE THREAD

**Issue by dambem** [dambem/ClimateMonitorV2#68]
## Description
So we have all of the API keys stored properly in git secrets, but the current work-around of giving people API keys isn't exactly the greatest solution. Using the API keys would be a lot better, especially if someone can work out how they work

**Comment by M-Davies** [comment]
From the secrets page in github:
> Secrets are environment variables that are encrypted and only exposed to selected actions. Anyone with collaborator access to this repository can use these secrets in a workflow. 

Also see https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository. From what I've gathered reading this, you would need to make us all admins of this repo to be able to use the secrets you declare in the repo. And even then, we can't see them, only update them.

IMO I don't think storing the secrets in GH is a good idea as the secrets are only visible to GH workflows and not to the developers who work on it. As an alternative, we could use [dotenv](https://www.npmjs.com/package/dotenv) to declare environment variables at startup and then import them directly into our application via `process.env.foobar`. That doesn't resolve the issue of transferring the secret to the developer who needs them in the first place however

**Comment by dambem** [comment]
Ahh I see, that makes sense. Cheers for looking that up! That might be the best bet in that case, I think just transferring the API keys directly might just have to happen as i don't see a great alternative
