### ISSUE TITLE
Hiding API Keys 

### ISSUE THREAD

**Issue by JonahLuckett** [dambem/ClimateMonitorV2#81]
## Description
Adding a vault or similar private storage for the API keys.

**Comment by M-Davies** [comment]
A few options for this:
- https://git-secret.io/. Complex but seems to integrate well with Git. The standard for git repos. ~The only one of these to work on windows without cygwin~ That's a lie, it also doesn't even work on cygwin but the feature is planned. I think we can rule out this option
- https://www.agwa.name/projects/git-crypt/. Easier to understand than git secret but with less features. Another standard for git repos
- https://github.com/StackExchange/blackbox. Easier to understand and lots of documentation, my personal favorite. However, it doesn't work on windows without Cygwin

Those are just the ones I found in a quick 10minute google. There are likely more. Opinions on the ones above (or any that I may have missed)?

**Comment by M-Davies** [comment]
Blackbox proved not to be the wonderful thing that I had hoped so [it is being removed](https://github.com/dambem/ClimateMonitorV2/pull/114) and this is an open issue again. My thinking now is to use a webpack and environment variables, roughly following [this guide](https://medium.com/@trekinbami/using-environment-variables-in-react-6b0a99d83cf5) to help me figure it out

**Comment by M-Davies** [comment]
I'm going to close this as we ended up using the original config method which proved to be the most reliable and (arguably) the most secure
