### ISSUE TITLE
Petty Styling improvements 

### ISSUE THREAD

**Issue by dambem** [dambem/ClimateMonitorV2#98]
## Description
Look at these ugly cards holding everything. so much weird wasted space and the pollution guidelines section looks so weird cause it's not the height of everything else (as it's set for a pixel value). Here's my suggested improvements
### General Styling Improvements
Stuff needs to get moved to percentages, no more pixels on that stylesheets apart from borders! 
### Specific and very nitpicky improvements
- [ ] 1. Make sure that the pollution guidelines isn't just an arbitrary pixel value
- [x] 2. Move around some of the cards so it makes more logical sense (What would the user be searching for first?)
- [x] 3. The margin-left and margin-right of the cards are a little off, think they can be made slightly smaller (and percentaged!)
- [x] 4. The borders look too bootstrappy, maybe a slight border shadow/inset could help it (or just change the colours and make it smaller)
- [x] 5. The colours of the carousel aren't right, and should be based on another colour on the website (maybe the light blue of the sidebar?) Also the left and right arrows shouldn't really need a background.
![image](https://user-images.githubusercontent.com/18164343/88176795-bd49bc00-cc1f-11ea-9f37-8822bf8b120f.png)

- [x] 1. The top logo needs to be slightly higher, and the bottom logo needs to be slightly lower
- [x] 2. Each section in the sidebar should have a logo, especially now we're adding a few more sections.)

![image](https://user-images.githubusercontent.com/18164343/88176298-f5043400-cc1e-11ea-9f5c-e0293ff829dc.png)

## The actual vs expected behaviour
It needs to look nicer

## Additional Information
I'm slightly insane

**Comment by M-Davies** [comment]
>  1. Make sure that the pollution guidelines isn't just an arbitrary pixel value

[The problem with this is that canvas elements need to have an initial height value](https://stackoverflow.com/a/18680851). Everything else has been implemented.
